version: "3"
services:
  stock-app:
    build: .
    environment:
      - PORT=80
    ports:
      - "80:80"
    volumes:
      - /etc/letsencrypt/live/stocks.sunli.co:/etc/letsencrypt/live/stocks.sunli.co
